window.SEARCH_DATA = {
    web: {name: '网页', placeholder: '网页搜索', list: [{'name':'百度','site':'https://www.baidu.com/s?wd=keywords'},{'name':'谷歌','site':'https://www.google.com/#q=keywords'},{'name':'必应','site':'https://www.bing.com/search?q=keywords'},{'name':'搜狗','site':'https://www.sogou.com/web?query=keywords'},{'name':'好搜','site':'https://www.so.com/s?q=keywords'},{'name':'搜微信','site':'http://weixin.sogou.com/weixin?type=2&query=keywords'},{'name':'搜知乎','site':'http://zhihu.sogou.com/zhihu?query=keywords'},{'name':'Yandex','site':'https://www.yandex.com/search/?text=keywords'}]},
    movie: {name: '影视', placeholder: '最新电影，高清电影', list: [{'name':'疯狂影视搜索','site':'http://ifkdy.com/?q=keywords'},{'name':'电影首发站','site':'http://www.dysfz.cc/key/keywords/'},{'name':'蓝光网','site':'http://www.languang.co/?s=keywords'},{'name':'天天美剧','site':'http://www.ttmeiju.com/index.php/search/index.html?keyword=keywords'},{'name':'动漫花园','site':'https://share.dmhy.org/topics/list?keyword=keywords'},{'name':'ACG搜','site':'http://www.acgsou.com/search.php?keyword=keywords'}]},
    cloudpan: {name: '网盘', placeholder: '网盘搜索', list: [{'name':'去转盘','site':'http://www.quzhuanpan.com/source/search.action?q=keywords&currentPage=1'},{'name':'胖次搜索','site':'https://www.panc.cc/s/keywords/'},{'name':'天天云搜','site':'http://so.ygyhg.com/s?keyword=keywords'},{'name':'呆木瓜','site':'http://md5.daimugua.com/search.aspx?q=keywords'},{'name':'鸵鸟搜索','site':'http://www.tuoniao.me/search/keywords/list'},{'name':'网盘007','site':'http://wangpan007.com/share/kwkeywords'}]},
    bt: {name: 'BT种子', placeholder: 'BT种子磁力链', list: [{'name':'BT之家','site':'http://www.btbtt.me/search-index-keyword-keywords.htm'},{'name':'片源网','site':'http://pianyuan.net/search?q=keywords'},{'name':'梦境搜索','site':'http://sou.mj0351.com/search.html?text=keywords'},{'name':'Btbook','site':'http://www.btmeet.org/search/keywords.html'},{'name':'BT云搜','site':'http://www.btyunsou.net/search/keywords_ctime_1.html'},{'name':'cilibaba','site':'http://www.cilisoba.net/search/keywords/'}]},
    software: {name: '软件', placeholder: '找软件', list: [{'name':'zd423','site':'http://www.zdfans.com/?s=keywords'},{'name':'吾爱破解','site':'http://zhannei.baidu.com/cse/search?q=keywords&click=1&s=14525262514411293706&isNeedCheckDomain=1&jump=1'},{'name':'殁漂遥','site':'http://www.shaoit.com/?s=keywords'},{'name':'胡萝卜周','site':'http://www.carrotchou.blog/?s=keywords'},{'name':'PC6','site':'http://s.pc6.com/cse/search?s=12026392560237532321&q=keywords'},{'name':'下载吧','site':'http://zhannei.baidu.com/cse/search?s=9035802123405734980&q=keywords'},{'name':'百度软件','site':'http://rj.baidu.com/search/index/?kw=keywords'}]},
    music: {name: '音乐', placeholder: '听音乐', list: [{'name':'网易云','site':'http://music.163.com/#/search/m/?s=keywords'},{'name':'虾米','site':'http://www.xiami.com/search?key=keywords'},{'name':'qq音乐','site':'http://y.qq.com/portal/search.html#searchid=1&remoteplace=txt.yqq.top&t=song&w=keywords'},{'name':'360音乐','site':'http://s.music.so.com/s?q=keywords'},{'name':'百度音乐','site':'http://music.baidu.com/search?key=keywords'},{'name':'音悦台','site':'http://so.yinyuetai.com/?keyword=keywords'},{'name':'酷狗','site':'http://www.kugou.com/yy/html/search.html#searchType=song&searchKeyWord=keywords'}]},
    sucai: {name: '素材', placeholder: '找素材', list: [{'name':'Iconfont图标','site':'http://www.iconfont.cn/search/index?searchType=icon&q=keywords'},{'name':'pixabay图片','site':'https://pixabay.com/zh/photos/?&q=keywords'},{'name':'花瓣','site':'http://huaban.com/search/?q=keywords'},{'name':'图鱼纹理','site':'http://www.hituyu.com/?q=keywords'},{'name':'搜GIF','site':'http://www.soogif.com/search/1/keywords'},{'name':'百度图片','site':'http://image.baidu.com/search/index?tn=baiduimage&ie=utf-8&word=keywords'}]},
    book: {name: '电子书', placeholder: '电子书，Kindle', list: [{'name':'我的小书屋','site':'http://mebook.cc/?s=keywords'},{'name':'Blah书库','site':'http://blah.me/search?q=keywords'},{'name':'鸠摩搜书','site':'https://www.jiumodiary.com/'},{'name':'走读派','site':'http://www.zoudupai.com/book/share?kw=keywords'},{'name':'azw3贴吧','site':'http://tieba.baidu.com/f/search/res?ie=utf-8&kw=azw3&qw=keywords'},{'name':'Gitbook','site':'https://www.gitbook.com/search?q=keywords'}]}
}